server:
  port: 9004
spring:
  application:
    name: cor-article #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.37.149.133:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true

  redis:
    host: 101.37.149.133
eureka:
  client:
    service-url:
      defaultZone: http://eureka6868.com:6868/eureka/
  #      解决跨域问题
  instance:
    prefer-ip-address: true
