server:
  port: 9001
spring:
  application:
    name: cor-database

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.149.133:3306/tensquare_base?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true