server:
  port: 9001
spring:
  application:
    name: cor-database

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.37.149.133:3306/tensquare_base?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka6868.com:6868/eureka/
  #      解决跨域问题
  instance:
    prefer-ip-address: true
