server: 
  port: 9005
spring: 
  application:  
    name: cor-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.37.149.133:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
