server:
  port: 3344

spring:
  application:
    name: application-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiaojiaoyow/cor.git
          search-paths: application_config
  rabbitmq:
    host: 101.37.149.133
#    有两个注意点：
#    1. 首先更新git文件时需要访问配置中心的（127.0.0.1：3344/actuator/bus-refresh）
#    2. 其次，自定义的配置要想更新生效，必须加注解@RefreshScope
  management:   # 暴露触发消息总线的地址
    endpoint:
      web:
        exposure:
          include: bus-refresh
