server:
  port: 3344

spring:
  application:
    name: application-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiaojiaoyow/cor.git
          search-paths: application_config
