server: 
  port: 9003
spring: 
  application:  
    name: cor-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.37.149.133:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka6868.com:6868/eureka/
  #      解决跨域问题
  instance:
    prefer-ip-address: true

#打开熔断器
feign:
  hystrix:
    enabled: true


jwt:
  config:
    key: test
    ttl: 3600000