server: 
  port: 9008
spring:

  application:  
    name: cor-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.37.149.133:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 101.37.149.133
  redis:
    host: 101.37.149.133

jwt:
  config:
    key: test
    ttl: 3600000